spring:
#  kafka:
#    bootstrap-servers: 10.10.10.21:6667,10.10.10.22:6667
#    consumer:
#      group-id: myGroup
#    template:
#      default-topic: my-replicated-topic
#    listener:
#      concurrency: 3
#    producer:
#      batch-size: 1000
  kafka:
    bootstrap-servers: 10.10.10.21:6667,10.10.10.22:6667
  jpa:
    properties:
      hibernate:
        show_sql: false
    hibernate:
      ddl-auto: none
  datasource:
      url: jdbc:mysql://10.10.10.252:3306/dota2?characterEncoding=utf-8&useSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver